/*
 * Copyright 2025 Yeong-won Seo
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "pch.h"
#include <mllif/Backend/C++/CxxDeclGen.h>

namespace mllif {
    extern auto Indent(size_t size) -> std::string;
}

bool mllif::cxx::CxxDeclGen::handleAssemblyBegin(MLLIFContext &context, const AssemblyDecl &node, std::ostream &out, std::size_t indent) {
    out << "// <auto-generated/>\n"
           "#include <cstdint>\n";
    return true;
}

bool mllif::cxx::CxxDeclGen::handleObjectBegin(MLLIFContext &context, const ObjectDecl &node, std::ostream &out, std::size_t indent) {

    out << Indent(indent) << "class " << node.name() << ";\n";

    return false;
}
